artifacts_root: artifacts

data ingestion:
  root dir: artifacts/data_ingestion
  source: data/retail_price.csv
  data_dir: artifacts/data_ingestion
  STATUS_FILE: artifacts/data_ingestion/status.txt

data_validation:
  root_dir: artifacts/data_validation
  data_dir: artifacts/data_ingestion/retail_price.csv
  STATUS_FILE: artifacts/data_validation/status.txt

feature_extraction:
  root_dir: artifacts/feature_extraction
  data_dir: artifacts/data_ingestion/retail_price.csv
  STATUS_FILE: artifacts/feature_extraction/status.txt

cross_val:
  root_dir: artifacts/cross_val
  data_dir: artifacts/feature_extraction/features_extracted.csv
  final_train_data_path: artifacts/cross_val/data_for_final_train
  final_test_data_path: artifacts/cross_val/data_for_final_train
  best_model_params: artifacts/cross_val/best_model_params
  STATUS_FILE: artifacts/cross_val/status.txt

model_trainer:
  root_dir: artifacts/model_trainer
  final_train_data_path: artifacts/cross_val/data_for_final_train
  final_test_data_path: artifacts/cross_val/data_for_final_train  
  best_model_params: artifacts/cross_val/best_model_params
  STATUS_FILE: artifacts/model_trainer/status.txt

model_evaluation:
  root_dir: artifacts/model_evaluation
  final_test_data_path: artifacts/cross_val/data_for_final_train
  model_path: artifacts/model_trainer
  STATUS_FILE: artifacts/model_evaluation/status.txt